<div class="homepage">

	<div class="homeboxes">	
		<div class="home-box1">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pt002-home-box1')->toHtml() ?>
		</div>
		<div class="home-box2">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pt002-home-box2')->toHtml() ?>
		</div>
		<div class="home-box3">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pt002-home-box3')->toHtml() ?>
		</div>
		<div class="home-box4">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pt002-home-box4')->toHtml() ?>
		</div>
		<div class="clearer"></div>
	</div>

</div>